### ISSUE TITLE
Request: Imgur Account Support

### ISSUE THREAD

**Issue by ghost** [cybre/budgie-screenshot-applet#40]
Is it at all possible for the applet to upload screenshots to a specific imgur account? I like the ability to take photos down if theres a reveal of privacy

**Comment by EbonJaeger** [comment]
@cybre if you want, I should be able to implement this and send a PR. Was wondering if you had any preferences regarding how it should be implemented; simplest would probably be to attach a new settings UI to the current Imgur Provider to store the credentials.

I think the only tricky part is getting the user's access token from Imgur.

**Comment by cybre** [comment]
@Gnat008 correct. Take a look at the S/FTP provider for the settings UI.
And yeah, that is indeed the tricky part.

**Comment by EbonJaeger** [comment]
@cybre My current idea is to have a button in the Imgur settings page that the user clicks, which calls out to the Imgur API endpoint to generate the needed tokens, and storing those in non-editable fields in the same settings page.

Currently it looks like this: https://i.imgur.com/Yl6mhcp.png

Only thing is that access tokens expire after one month, after which you can use the refresh token to get a new one. So that has to be handled.
